/**
 * Constants and Configuration for Accessibility Audit
 */

/** Valid ARIA roles */
export const VALID_ARIA_ROLES = new Set([
  'alert',
  'alertdialog',
  'application',
  'article',
  'banner',
  'button',
  'cell',
  'checkbox',
  'columnheader',
  'combobox',
  'complementary',
  'contentinfo',
  'definition',
  'dialog',
  'directory',
  'document',
  'feed',
  'figure',
  'form',
  'grid',
  'gridcell',
  'group',
  'heading',
  'img',
  'link',
  'list',
  'listbox',
  'listitem',
  'log',
  'main',
  'marquee',
  'math',
  'menu',
  'menubar',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'navigation',
  'none',
  'note',
  'option',
  'presentation',
  'progressbar',
  'radio',
  'radiogroup',
  'region',
  'row',
  'rowgroup',
  'rowheader',
  'scrollbar',
  'search',
  'searchbox',
  'separator',
  'slider',
  'spinbutton',
  'status',
  'switch',
  'tab',
  'table',
  'tablist',
  'tabpanel',
  'term',
  'textbox',
  'timer',
  'toolbar',
  'tooltip',
  'tree',
  'treegrid',
  'treeitem',
]);

/** Valid ARIA states and properties */
export const VALID_ARIA_STATES = new Set([
  'aria-atomic',
  'aria-autocomplete',
  'aria-busy',
  'aria-checked',
  'aria-colcount',
  'aria-colindex',
  'aria-colspan',
  'aria-controls',
  'aria-current',
  'aria-describedby',
  'aria-details',
  'aria-disabled',
  'aria-dropeffect',
  'aria-errormessage',
  'aria-expanded',
  'aria-flowto',
  'aria-grabbed',
  'aria-haspopup',
  'aria-hidden',
  'aria-invalid',
  'aria-keyshortcuts',
  'aria-label',
  'aria-labelledby',
  'aria-level',
  'aria-live',
  'aria-modal',
  'aria-multiline',
  'aria-multiselectable',
  'aria-orientation',
  'aria-owns',
  'aria-placeholder',
  'aria-posinset',
  'aria-pressed',
  'aria-readonly',
  'aria-relevant',
  'aria-required',
  'aria-roledescription',
  'aria-rowcount',
  'aria-rowindex',
  'aria-rowspan',
  'aria-selected',
  'aria-setsize',
  'aria-sort',
  'aria-valuemax',
  'aria-valuemin',
  'aria-valuenow',
  'aria-valuetext',
]);

/** Selector for focusable elements */
export const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
  '[contenteditable]:not([contenteditable="false"])',
  'area[href]',
  'details > summary',
  'iframe',
  'object[usemap]',
  'audio[controls]',
  'video[controls]',
  '[contenteditable]',
].join(', ');

/** Interactive elements that need accessible names */
export const INTERACTIVE_ELEMENTS = ['a', 'button', 'input', 'select', 'textarea'];

/** Text elements to check for contrast */
export const TEXT_CONTRAST_SELECTOR =
  'p, h1, h2, h3, h4, h5, h6, span, a, button, label, li, td, th, figcaption, blockquote';

/** Landmark roles for validation */
export const LANDMARK_ROLES = new Set([
  'banner',
  'complementary',
  'contentinfo',
  'form',
  'main',
  'navigation',
  'region',
  'search',
]);

/** Landmark elements (HTML5 semantic elements) */
export const LANDMARK_ELEMENTS = new Set([
  'header',
  'aside',
  'footer',
  'form',
  'main',
  'nav',
  'section',
]);

/** Color constants for UI */
export const COLORS = {
  error: '#ef4444',
  warning: '#f59e0b',
  info: '#3b82f6',
  success: '#22c55e',
  primary: '#6366f1',
  primaryLight: '#818cf8',
  bgDark: 'rgba(15, 23, 42, 0.98)',
  bgPanel: 'rgba(30, 41, 59, 0.8)',
  bgPanelLight: 'rgba(30, 41, 59, 0.5)',
  textPrimary: '#e2e8f0',
  textSecondary: '#94a3b8',
  textMuted: '#64748b',
  accent: '#c084fc',
} as const;

/** Z-index values for overlays */
export const Z_INDEX = {
  panel: 2147483647,
  overlay: 2147483646,
  highlight: 2147483645,
} as const;
