import type { Metadata } from "next";
import { headers } from "next/headers";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { TOOL_COUNT } from "@/data/tools";
import "./globals.css";

export const metadata: Metadata = {
  title: `FrontendDevHelper — ${TOOL_COUNT} Visual Debugging Tools in One Browser Extension`,
  description: `Stop juggling 12 legacy extensions. FrontendDevHelper unifies ${TOOL_COUNT} professional visual debugging tools into one Manifest V3 browser extension. 100% free & open source.`,
  keywords: [
    "browser extension",
    "frontend developer tools",
    "chrome extension",
    "web debugging",
    "dom inspector",
    "css inspector",
    "accessibility audit",
  ],
  metadataBase: new URL("https://frontenddevhelper.com"),
  openGraph: {
    title: `FrontendDevHelper — ${TOOL_COUNT} Visual Debugging Tools in One Browser Extension`,
    description: `${TOOL_COUNT} professional visual debugging tools in one Manifest V3 browser extension. Free & open source.`,
    url: "https://frontenddevhelper.com",
    siteName: "FrontendDevHelper",
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `FrontendDevHelper — ${TOOL_COUNT} Visual Debugging Tools in One Extension`,
    description: `Replace 12 legacy extensions with one. ${TOOL_COUNT} professional tools. Free & open source.`,
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Per-request CSP nonce generated by middleware; stamped on inline/external
  // scripts so the nonce-based CSP doesn't block them.
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <head>
        <script
          defer
          nonce={nonce}
          data-domain="frontenddevhelper.com"
          src="https://plausible.io/js/script.js"
        />
      </head>
      <body className="bg-bg-base text-text-secondary antialiased">
        {children}
      </body>
    </html>
  );
}
