/**
 * HTML Exporter
 *
 * Handles HTML/PDF export generation
 */

import { escapeHtml } from '@/utils/sanitize';
import { DEFAULT_PDF_OPTIONS } from '../constants';
import type { PDFOptions } from '../types';

/**
 * Generate PDF HTML template
 * @param data - Data to export
 * @param options - PDF generation options
 * @returns HTML string
 */
export function generatePDFHtml(data: object, options?: Partial<PDFOptions>): string {
  const finalOptions = {
    ...DEFAULT_PDF_OPTIONS,
    ...options,
  };

  const { title, subtitle, includeHeader, includeFooter, theme } = finalOptions;
  const isDark = theme === 'dark';
  const bgColor = isDark ? '#1f2937' : '#ffffff';
  const textColor = isDark ? '#f3f4f6' : '#1f2937';
  const borderColor = isDark ? '#374151' : '#e5e7eb';

  const formattedData = escapeHtml(JSON.stringify(data, null, 2));

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: system-ui, -apple-system, sans-serif;
      background: ${bgColor};
      color: ${textColor};
      line-height: 1.6;
      padding: 40px;
      max-width: 210mm;
      margin: 0 auto;
    }
    ${
      includeHeader
        ? `
    .header {
      border-bottom: 2px solid ${borderColor};
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 { font-size: 24px; margin-bottom: 8px; }
    .header .subtitle { color: ${isDark ? '#9ca3af' : '#6b7280'}; font-size: 14px; }
    `
        : ''
    }
    .content { margin-bottom: 30px; }
    .section { margin-bottom: 24px; }
    .section-title {
      font-size: 16px;
      font-weight: 600;
      margin-bottom: 12px;
      padding-bottom: 8px;
      border-bottom: 1px solid ${borderColor};
    }
    pre {
      background: ${isDark ? '#111827' : '#f3f4f6'};
      padding: 16px;
      border-radius: 8px;
      overflow-x: auto;
      font-size: 12px;
      font-family: 'JetBrains Mono', monospace;
    }
    .meta-info {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 12px;
      font-size: 12px;
    }
    .meta-item { display: flex; justify-content: space-between; }
    .meta-label { color: ${isDark ? '#9ca3af' : '#6b7280'}; }
    ${
      includeFooter
        ? `
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid ${borderColor};
      font-size: 12px;
      color: ${isDark ? '#9ca3af' : '#6b7280'};
      text-align: center;
    }
    `
        : ''
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
    @page { margin: 20mm; }
  </style>
</head>
<body>
  ${
    includeHeader
      ? `
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<div class="subtitle">${escapeHtml(subtitle)}</div>` : ''}
  </div>
  `
      : ''
  }
  
  <div class="content">
    <div class="section">
      <div class="section-title">Export Data</div>
      <pre><code>${formattedData}</code></pre>
    </div>
    
    <div class="section">
      <div class="section-title">Report Metadata</div>
      <div class="meta-info">
        <div class="meta-item">
          <span class="meta-label">Generated:</span>
          <span>${new Date().toLocaleString()}</span>
        </div>
        <div class="meta-item">
          <span class="meta-label">URL:</span>
          <span>${escapeHtml(window.location.href)}</span>
        </div>
        <div class="meta-item">
          <span class="meta-label">Page Title:</span>
          <span>${escapeHtml(document.title)}</span>
        </div>
        <div class="meta-item">
          <span class="meta-label">Viewport:</span>
          <span>${window.innerWidth}×${window.innerHeight}</span>
        </div>
      </div>
    </div>
  </div>
  
  ${
    includeFooter
      ? `
  <div class="footer">
    Generated by Frontend Dev Helper Extension
  </div>
  `
      : ''
  }
  
  <div class="no-print" style="margin-top: 30px; text-align: center;">
    <button onclick="window.print()" style="
      padding: 12px 24px;
      background: #3b82f6;
      color: white;
      border: none;
      border-radius: 6px;
      cursor: pointer;
      font-size: 14px;
    ">Print / Save as PDF</button>
  </div>
</body>
</html>`;
}

/**
 * Export data as HTML/PDF file
 * @param data - Data to export
 * @param filename - Optional custom filename
 * @param options - PDF generation options
 * @returns Blob and filename
 */
export function exportAsHTML(
  data: object,
  filename?: string,
  options?: Partial<PDFOptions>
): { blob: Blob; filename: string } {
  const html = generatePDFHtml(data, options);
  const blob = new Blob([html], { type: 'text/html' });
  const finalFilename = filename
    ? `${filename}.html`
    : `export-${new Date().toISOString().split('T')[0]}.html`;

  return { blob, filename: finalFilename };
}
