/**
 * Live CSS Editor - CSS Editing Functionality
 */

import { MAX_HISTORY_SIZE } from './constants';
import { getModifiedElements, getSelectedElement, updateElementModifiedStyle } from './inspector';
import type { CSSEdit, CSSEditorOptions } from './types';
import { showNotification } from './ui';

// History state
const history: CSSEdit[] = [];
let historyIndex = -1;

// Options
let options: Required<CSSEditorOptions> = {
  highlightColor: '#8b5cf6',
  maxHistorySize: 50,
  onElementSelect: () => {},
  onStyleChange: () => {},
};

export function setOptions(newOptions: CSSEditorOptions): void {
  options = { ...options, ...newOptions };
}

export function getOptions(): Required<CSSEditorOptions> {
  return options;
}

export function getHistory(): CSSEdit[] {
  return [...history];
}

export function getHistoryIndex(): number {
  return historyIndex;
}

export function applyStyle(property: string, value: string): void {
  const selectedElement = getSelectedElement();
  if (!selectedElement) return;

  const oldValue =
    selectedElement.style.getPropertyValue(property) ||
    window.getComputedStyle(selectedElement).getPropertyValue(property);

  // Apply the style
  selectedElement.style.setProperty(property, value, 'important');

  // Track the modification
  updateElementModifiedStyle(selectedElement, property, value);

  // Add to history
  addToHistory({
    property,
    oldValue,
    newValue: value,
    timestamp: Date.now(),
  });

  // Notify callback
  options.onStyleChange(selectedElement, property, value);
}

function addToHistory(edit: CSSEdit): void {
  // Remove any redo entries
  if (historyIndex < history.length - 1) {
    history.splice(historyIndex + 1);
  }

  // Add new edit
  history.push(edit);
  historyIndex++;

  // Trim history if needed
  if (history.length > MAX_HISTORY_SIZE) {
    history.shift();
    historyIndex--;
  }

  // Store edit on element data
  const selectedElement = getSelectedElement();
  if (selectedElement) {
    const modifiedElements = getModifiedElements();
    const elementData = modifiedElements.get(selectedElement);
    if (elementData) {
      elementData.edits.push(edit);
    }
  }
}

export function undo(): void {
  if (historyIndex < 0) return;

  const edit = history[historyIndex];
  const selectedElement = getSelectedElement();

  if (selectedElement) {
    selectedElement.style.setProperty(edit.property, edit.oldValue);

    const modifiedElements = getModifiedElements();
    const elementData = modifiedElements.get(selectedElement);
    if (elementData) {
      if (edit.oldValue) {
        elementData.modifiedStyles.set(edit.property, edit.oldValue);
      } else {
        elementData.modifiedStyles.delete(edit.property);
      }
    }
  }

  historyIndex--;
}

export function redo(): void {
  if (historyIndex >= history.length - 1) return;

  historyIndex++;
  const edit = history[historyIndex];
  const selectedElement = getSelectedElement();

  if (selectedElement) {
    selectedElement.style.setProperty(edit.property, edit.newValue, 'important');

    const modifiedElements = getModifiedElements();
    const elementData = modifiedElements.get(selectedElement);
    if (elementData) {
      elementData.modifiedStyles.set(edit.property, edit.newValue);
    }
  }
}

export function resetElement(): void {
  const selectedElement = getSelectedElement();
  if (!selectedElement) return;

  const modifiedElements = getModifiedElements();
  const elementData = modifiedElements.get(selectedElement);
  if (elementData) {
    // Restore original styles
    elementData.modifiedStyles.forEach((_, property) => {
      const originalValue = elementData.originalStyles.get(property) || '';
      selectedElement.style.setProperty(property, originalValue);
    });

    // Clear modifications
    elementData.modifiedStyles.clear();
    elementData.edits = [];
  }
}

export function generateCSS(): string {
  const selectedElement = getSelectedElement();
  if (!selectedElement) return '';

  const modifiedElements = getModifiedElements();
  const elementData = modifiedElements.get(selectedElement);
  if (!elementData || elementData.modifiedStyles.size === 0) {
    return '/* No styles modified */';
  }

  const selector = elementData.selector;
  let css = `${selector} {\n`;

  elementData.modifiedStyles.forEach((value, property) => {
    css += `  ${property}: ${value};\n`;
  });

  css += '}';
  return css;
}

export function copyCSS(): void {
  const css = generateCSS();
  navigator.clipboard.writeText(css).then(() => {
    showNotification('CSS copied to clipboard!');
  });
}

export function exportAllCSS(): string {
  const modifiedElements = getModifiedElements();
  let css = '/* Generated by Live CSS Editor */\n\n';

  modifiedElements.forEach((data) => {
    if (data.modifiedStyles.size > 0) {
      css += `${data.selector} {\n`;
      data.modifiedStyles.forEach((value, property) => {
        css += `  ${property}: ${value};\n`;
      });
      css += '}\n\n';
    }
  });

  return css;
}

export function resetAll(): void {
  const modifiedElements = getModifiedElements();
  modifiedElements.forEach((data, element) => {
    data.modifiedStyles.forEach((_, property) => {
      const originalValue = data.originalStyles.get(property) || '';
      element.style.setProperty(property, originalValue);
    });
    data.modifiedStyles.clear();
    data.edits = [];
  });

  history.length = 0;
  historyIndex = -1;
}

export function cleanup(): void {
  history.length = 0;
  historyIndex = -1;
}
