import type { AuditResult, AuditIssue } from './export-service';

export interface GitHubConfig {
  token: string;
  enabled: boolean;
}

export interface PRInfo {
  owner: string;
  repo: string;
  prNumber: number;
}

export function detectPRFromUrl(url: string): PRInfo | null {
  const pattern = /github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/;
  const match = url.match(pattern);
  if (!match) return null;
  return { owner: match[1], repo: match[2], prNumber: parseInt(match[3]) };
}

export async function validateToken(token: string): Promise<{ valid: boolean; username?: string; error?: string }> {
  if (!token) return { valid: false, error: 'Token is required' };
  try {
    const response = await fetch('https://api.github.com/user', {
      headers: { Authorization: `token ${token}` },
    });
    if (!response.ok) {
      return { valid: false, error: `GitHub returned ${response.status}` };
    }
    const data = await response.json();
    return { valid: true, username: data.login };
  } catch (error) {
    return { valid: false, error: error instanceof Error ? error.message : 'Connection failed' };
  }
}

export async function postPRComment(
  token: string,
  prInfo: PRInfo,
  body: string,
): Promise<{ success: boolean; url?: string; error?: string }> {
  try {
    const response = await fetch(
      `https://api.github.com/repos/${prInfo.owner}/${prInfo.repo}/issues/${prInfo.prNumber}/comments`,
      {
        method: 'POST',
        headers: {
          Authorization: `token ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ body }),
      },
    );
    if (!response.ok) {
      const errorBody = await response.text().catch(() => '');
      return { success: false, error: `GitHub API ${response.status}: ${errorBody}` };
    }
    const data = await response.json();
    return { success: true, url: data.html_url };
  } catch (error) {
    return { success: false, error: error instanceof Error ? error.message : 'Request failed' };
  }
}

function severityEmoji(severity: string): string {
  switch (severity) {
    case 'critical': return ':red_circle:';
    case 'serious': return ':large_orange_diamond:';
    case 'moderate': return ':large_yellow_circle:';
    case 'minor': return ':large_blue_circle:';
    default: return ':white_circle:';
  }
}

function scoreBadge(score: number): string {
  if (score >= 90) return ':white_check_mark:';
  if (score >= 50) return ':warning:';
  return ':x:';
}

export function formatAuditAsGitHubComment(result: AuditResult): string {
  const lines: string[] = [];
  lines.push('## :mag: FDH Audit Report');
  lines.push('');
  lines.push(`**URL:** ${result.url}`);
  lines.push(`**Date:** ${new Date(result.timestamp).toISOString().replace('T', ' ').slice(0, 19)}`);
  lines.push(`**Overall Score:** ${scoreBadge(result.overallScore)} **${result.overallScore}/100**`);
  lines.push('');

  const catEntries = Object.entries(result.categories) as [
    string,
    { score: number; issues: AuditIssue[] },
  ][];

  lines.push('| Category | Score | Issues |');
  lines.push('|----------|-------|--------|');
  for (const [key, cat] of catEntries) {
    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
    const critical = cat.issues.filter((i) => i.severity === 'critical' || i.severity === 'serious').length;
    lines.push(`| ${label} | ${scoreBadge(cat.score)} ${cat.score}/100 | ${critical > 0 ? `**${critical} critical** / ` : ''}${cat.issues.length} total |`);
  }
  lines.push('');

  for (const [key, cat] of catEntries) {
    if (cat.issues.length === 0) continue;
    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
    lines.push(`<details>`);
    lines.push(`<summary><strong>${label}</strong> — ${cat.issues.length} issue${cat.issues.length !== 1 ? 's' : ''}</summary>`);
    lines.push('');
    lines.push('| Severity | Title | Description | Fix |');
    lines.push('|----------|-------|-------------|-----|');
    for (const issue of cat.issues) {
      const title = issue.title.replace(/\|/g, '\\|');
      const desc = issue.description.replace(/\|/g, '\\|').slice(0, 100);
      const fix = (issue.suggestedFix || '—').replace(/\|/g, '\\|').slice(0, 80);
      lines.push(`| ${severityEmoji(issue.severity)} ${issue.severity} | ${title} | ${desc} | ${fix} |`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [Frontend Dev Helper](https://github.com/frontend-dev-helper)*');
  return lines.join('\n');
}
